export const data = [
  {
    title: 'Андрей',
    preview: 'Изображение',
    date: '10:49',
    count: '2',
  },
  {
    title: 'Киноклуб',
    preview: 'Вы: стикер',
    date: '12:00',
    count: '',
  },
  {
    title: 'Илья',
    preview: 'Друзья, у меня для вас особенный выпуск новостей!...',
    date: '15:12',
    count: '4',
  },
  {
    title: 'Вадим',
    preview: 'Вы: Круто!',
    date: 'Пт',
    count: '',
  },
  {
    title: 'тет-а-теты',
    preview: 'И Human Interface Guidelines и Material Design рекомендуют...',
    date: 'Ср',
    count: '',
  },
  {
    title: '1, 2, 3',
    preview: 'Миллионы россиян ежедневно проводят десятки часов свое...',
    date: 'Пн',
    count: '',
  },
  {
    title: 'Design Destroyer',
    preview: 'В 2008 году художник Jon Rafman начал собирать...',
    date: 'Пн',
    count: '',
  },
  {
    title: 'Day.',
    preview: 'Так увлёкся работой по курсу, что совсем забыл его анонсир...',
    date: '1 Мая 2020',
    count: '',
  },
  {
    title: 'Стас Рогозин',
    preview: 'Можно или сегодня или завтра вечером.',
    date: '12 Апр 2020',
    count: '',
  },
  {
    title: 'Design Destroyer',
    preview: 'В 2008 году художник Jon Rafman начал собирать...',
    date: 'Пн',
    count: '',
  },
  {
    title: 'Day.',
    preview: 'Так увлёкся работой по курсу, что совсем забыл его анонсир...',
    date: '1 Мая 2020',
    count: '',
  },
  {
    title: 'Стас Рогозин',
    preview: 'Можно или сегодня или завтра вечером.',
    date: '12 Апр 2020',
    count: '',
  },
  {
    title: 'Стас Рогозин',
    preview: 'Можно или сегодня или завтра вечером.',
    date: '12 Апр 2020',
    count: '',
  },
  {
    title: 'Design Destroyer',
    preview: 'В 2008 году художник Jon Rafman начал собирать...',
    date: 'Пн',
    count: '',
  },
  {
    title: 'Day.',
    preview: 'Так увлёкся работой по курсу, что совсем забыл его анонсир...',
    date: '1 Мая 2020',
    count: '',
  },
  {
    title: 'Стас Рогозин',
    preview: 'Можно или сегодня или завтра вечером.',
    date: '12 Апр 2020',
    count: '',
  },
];
